backend:
  name: git-gateway
  branch: main # Change this to your default branch

# Uncomment if you want to use local development
# local_backend: true

media_folder: "assets"
public_folder: "/assets"

collections:
  # Documentation pages
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # UX pages
  - name: "ux"
    label: "User Experiences"
    folder: "ux"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # UX - Core UI pages
  - name: "ux-core-ui"
    label: "UX - Core UI"
    folder: "ux/core-ui"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # UX - Service Portal pages
  - name: "ux-service-portal"
    label: "UX - Service Portal"
    folder: "ux/service-portal"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # UX - Next Experience pages
  - name: "ux-next-experience"
    label: "UX - Next Experience"
    folder: "ux/next-experience"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Data pages
  - name: "data"
    label: "Data"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Automations pages
  - name: "automations"
    label: "Automations"
    folder: "automations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Access pages
  - name: "access"
    label: "Access"
    folder: "access"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Products pages
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Settings
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "settings.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Favicon URL", name: "faviconUrl", widget: "string"}
          - {label: "Blog Title", name: "blogTitle", widget: "string"}
          - {label: "Edit This Page Root URL", name: "editThisPageRootUrl", widget: "string"}
          - {label: "Search Enabled", name: "searchEnabled", widget: "boolean"}
          - {label: "Language", name: "lang", widget: "string"}
          - label: "Highlight.js Languages"
            name: "hljsLanguages"
            widget: "list"
            default: ["xml", "javascript", "json", "yaml", "liquid", "markdown", "css"]
