backend:
  name: git-gateway
  branch: main

# Uncomment if you want to use local development
# local_backend: true

media_folder: "assets"
public_folder: "/assets"

collections:
  # Documentation
  - name: "docs"
    label: "üìö Documentation"
    folder: "docs"
    create: true
    nested:
      depth: 100
    meta: {path: {widget: string, label: 'Path', index_file: 'index'}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false, collapsed: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # User Experiences (with all subfolders)
  - name: "ux"
    label: "üé® User Experiences"
    folder: "ux"
    create: true
    nested:
      depth: 100
    meta: {path: {widget: string, label: 'Path', index_file: 'index'}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false, collapsed: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Data
  - name: "data"
    label: "üíæ Data"
    folder: "data"
    create: true
    nested:
      depth: 100
    meta: {path: {widget: string, label: 'Path', index_file: 'index'}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false, collapsed: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Automations
  - name: "automations"
    label: "‚öôÔ∏è Automations"
    folder: "automations"
    create: true
    nested:
      depth: 100
    meta: {path: {widget: string, label: 'Path', index_file: 'index'}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false, collapsed: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Access
  - name: "access"
    label: "üîí Access"
    folder: "access"
    create: true
    nested:
      depth: 100
    meta: {path: {widget: string, label: 'Path', index_file: 'index'}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false, collapsed: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Products
  - name: "products"
    label: "üì¶ Products"
    folder: "products"
    create: true
    nested:
      depth: 100
    meta: {path: {widget: string, label: 'Path', index_file: 'index'}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "libdoc_page.liquid"}
      - label: "Eleventy Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key", name: "key", widget: "string", required: false}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "hidden", default: "git Last Modified"}
      - {label: "Tags", name: "tags", widget: "list", required: false, collapsed: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Settings
  - name: "settings"
    label: "‚öôÔ∏è Site Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "settings.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Favicon URL", name: "faviconUrl", widget: "string"}
          - {label: "Blog Title", name: "blogTitle", widget: "string"}
          - {label: "Edit This Page Root URL", name: "editThisPageRootUrl", widget: "string"}
          - {label: "Search Enabled", name: "searchEnabled", widget: "boolean"}
          - {label: "Language", name: "lang", widget: "string"}
          - label: "Highlight.js Languages"
            name: "hljsLanguages"
            widget: "list"
            default: ["xml", "javascript", "json", "yaml", "liquid", "markdown", "css"]
